# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Makrosum\MeetingBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        MakrosumAuthentication:
            entity:
                class: MeetingBundle:User
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: MakrosumAuthentication
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
                login_path: login_www
                check_path: login_www
                target_path_parameter: _target_path
                failure_path: login_www
                use_referer: true
            logout:
                path: logout
                target: /
    access_control:
        - { path: ^/b409d457e31a.html, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/global, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/load/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/test, roles: ROLE_USER }
        - { path: ^/, host: 'www\.%hostname%', roles: ROLE_USER }
        - { path: ^/company, host: '((?!www\.))\.%hostname%', roles: ROLE_USER }
        - { path: ^/company, host: '((?!www\.))\.%hostname%', roles: ROLE_USER }
        - { path: ^/, host: '((?!www\.))\.%hostname%', roles: IS_AUTHENTICATED_ANONYMOUSLY }
    role_hierarchy:
        ROLE_ADMIN:     [ROLE_USER, IS_AUTHENTICATED_ANONYMOUSLY]