<?php

namespace Makrosum\MeetingBundle\Repository;

/**
 * ActivationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivationRepository extends \Doctrine\ORM\EntityRepository
{
}
