<?php

namespace Makrosum\MeetingBundle\Repository;
use Makrosum\MeetingBundle\Abstractions\MakrosumRepository;
use Makrosum\MeetingBundle\Entity\Company;
use Makrosum\MeetingBundle\Entity\Department;

/**
 * DepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends MakrosumRepository
{
    public function findAllDepartments(Company $Company)
    {
        return $this->findBy([
            "company" => $Company->getId()
        ]);
    }
}
