<?php

namespace Makrosum\MeetingBundle\Repository;

/**
 * MeetingReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingReportRepository extends \Doctrine\ORM\EntityRepository
{
}
