<?php

namespace Makrosum\MeetingBundle\Repository;

/**
 * MeetingMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
