<?php

namespace Makrosum\MeetingBundle\Repository;

/**
 * MeetingMatterSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingMatterSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
