<?php

namespace Makrosum\MeetingBundle\Repository;

/**
 * MeetingCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
