<?php

namespace Makrosum\MeetingBundle\Repository;
use Makrosum\MeetingBundle\Abstractions\MakrosumRepository;
use Makrosum\MeetingBundle\Entity\Department;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends MakrosumRepository
{
    public function findAllPositionsByDepartment(Department $Department)
    {
        return $this->findBy([
            "department" => $Department->getId()
        ], ["id" => "DESC"]);
    }
}
